### ISSUE TITLE
Strip "v" prefix off of tags

### ISSUE THREAD

**Issue by markjaquith** [10up/action-wordpress-plugin-deploy#1]
In Git, it is common to prefix tagged versions with `v` (e.g. `v1.2.3`), but in the WordPress SVN plugin directory, it's common to have no prefix (e.g. a tag of `1.2.3`).

It would be nice if this recognized these patterns and stripped the `v` prefix when committing the SVN tag.

**Comment by vincenzo** [comment]
It could use "stable tag" from the readme.txt or ... it could do some work like `semantic-release` does for Node.js packages, and let us leave "Stable tag" set to "semantic-tag" for example, and then edit the readme.txt (same would hold for other files that are known to hold a version number) on the fly before releasing to SVN.

**Comment by vincenzo** [comment]
Having been away from WP development for a while, and having just pushed 4 different releases to change the version in all the right places, I would back up my previous comment and ask for a `semantic-release` kind of approach, where plugin version is templated in readme and the main file at least.

**Comment by helen** [comment]
@vincenzo Is this related to the `v` prefix or are you wanting more automation around the version number? Actions can be chained, so I think you’re probably looking for something to handle that sort of templating for you that isn’t specific to the deployment task, but rather would run before it. I think it would also affect how you potentially use the separate asset updater Action.
