### ISSUE TITLE
Add "Getting started" steps

### ISSUE THREAD

**Issue by nielslange** [10up/action-wordpress-plugin-deploy#10]
@helen Thank you so much for your excellent work here! This is exactly what I've been looking for. Unfortunately, I'm unable to get the strict working on my end and I'm sure I'm done something terribly stupid. 😂

Here's what I did:

1. Headed over to https://github.com/marketplace/actions/wordpress-plugin-deploy
2. Copied the example workflow file
3. Headed over to my plugin repo and created the secrets and added the example workflow to the actions
4. Bumped up the version number of my plugin and pushed the changes to the repo

Nothing happened though. 🧐

While I do not expect that you offer any support for my individual issue, it would be great having some general "Getting started" steps.

**Comment by Nikschavan** [comment]
Hey, @nielslange This action works after you push a tag to GitHub as per the default workflow.
So - Each tag you push to GitHub will be pushed to W.org as an update.

Can you confirm if you also created a tag/release on GitHub?

**Comment by nielslange** [comment]
I did, @Nikschavan, and nothing happened. I bumped my plugin version from 1.6 to 1.6.1 and pushed the tag to `master`.

**Comment by nielslange** [comment]
@Nikschavan I found out what I did wrong. Instead of pushing the tag to the repo, I pushed master to the repo.
