### ISSUE TITLE
File names with @ not escaped

### ISSUE THREAD

**Issue by Stiofan** [10up/action-wordpress-plugin-deploy#13]
**Describe the bug**
➤ Preparing files...
svn: E200009: 'trunk/public/assets/images/chosen-sprite@2x.png': a peg revision is not allowed here
##[error]Docker run failed with exit code 123

File names with @ sign need to be escaped with double @@

**Comment by helen** [comment]
We could do something like appending an `@` to the end of every file name during add, it doesn't hurt anything.

@Stiofan Are you interested in working on a pull request?

**Comment by dinhtungdu** [comment]
I can't reproduce the issue. I tested with files with `@` in the filename at the root directory and subdirectory, no error.

You can check the result here: https://github.com/dinhtungdu/command-palette/commit/5cf234b5900a54af56d7d8db7e71fc7979bf4688/checks?check_suite_id=344928829

_I forked this repo and remove the svn commit part for testing._

**Comment by Gaya** [comment]
Think I solved it in #22. Seems like paths to be removed were not escaped.
