### ISSUE TITLE
Error when deplying

### ISSUE THREAD

**Issue by sebastienserre** [10up/action-wordpress-plugin-deploy#15]
Hello,

I try your action to test the deployment without SVN and got an error:

```
Run npm install
npm WARN saveError ENOENT: no such file or directory, open '/home/runner/work/messesinfo/messesinfo/package.json'
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN enoent ENOENT: no such file or directory, open '/home/runner/work/messesinfo/messesinfo/package.json'
npm WARN messesinfo No description
npm WARN messesinfo No repository field.
npm WARN messesinfo No README data
npm WARN messesinfo No license field.

up to date in 0.421s
found 0 vulnerabilities

npm ERR! code ENOENT
npm ERR! syscall open
npm ERR! path /home/runner/work/messesinfo/messesinfo/package.json
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, open '/home/runner/work/messesinfo/messesinfo/package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/runner/.npm/_logs/2019-11-20T10_01_58_134Z-debug.log
##[error]Process completed with exit code 254.```
Could you please help me ?
Many thanks by advance

**Comment by wolffe** [comment]
Same here. I have created a `package.json` file:

```
{
    "name": "wp-perfect-plugin",
    "version": "1.3.7.3",
    "description": "WP Perfect Plugin aims to provide advanced options for any web developer. WP Perfect Plugin has options for search engines, such as ownership verification, local business JSON-LD data, Open Graph, analytics, header and footer easy code insertion and optimised SEO defaults."
}
```

Now I'm only getting:

`npm ERR! Invalid version: "1.3.7.3"`

**Comment by wolffe** [comment]
UPDATE:

I changed the version to major.minor.feature (i.e. `1.3.8` in my case) and it worked. Now I'm only getting one error:

`npm ERR! missing script: build`

**Comment by helen** [comment]
@sebastienserre @wolffe These are `npm` errors which tell me that you’re not using a build process, so you will want to remove the following lines from the workflow file, no need for a skeleton `package.json` if you’re not doing anything with it.

```yaml
    - name: Build
      run: |
        npm install
        npm run build
```

**Comment by wolffe** [comment]
Thanks @helen 

I have actually added a build keyword in my `package.json` file and it worked. The next error, though is in the deploying part:

`svn: E155005: No write-lock in '/github/svn-wp-perfect-plugin/trunk'`

**Comment by sebastienserre** [comment]
no more error on my part, many thanks @helen

**Comment by wolffe** [comment]
Another one from me:

`svn: E155023: Cannot copy to '/github/svn-wp-perfect-plugin/tags/1.3.10', as it is not from repository 'https://plugins.svn.wordpress.org'; it is from 'http://plugins.svn.wordpress.org'`

**Comment by wolffe** [comment]
**UPDATE:**

It worked. I had an old (and hidden) `.svn` directory inside my plugin. I deleted it and it worked like magic.

Thanks @helen and thanks @10up!

**Comment by jeffpaul** [comment]
@sebastienserre @wolffe sounds like you're both all set, glad to here Helen was able to help get things settled for you.  Let us know if you run into any further issues or have ideas on how to improve our GitHub Actions... thanks!
