### ISSUE TITLE
Link to "encrypted secrets" GitHub Docs

### ISSUE THREAD

**Issue by felipeelia** [10up/action-wordpress-plugin-deploy#19]
**Describe the bug**

Probably GitHub has updated their docs and the `Secrets are set in your repository settings` link present on the README.md file points to the wrong page.

**Steps to Reproduce**

1. Go to repo's README.md
2. Click on `Secrets are set in your repository settings.`
3. The link points to the [Virtual environments for GitHub-hosted runners](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/virtual-environments-for-github-hosted-runners#creating-and-using-secrets-encrypted-variables) page but the related section isn't there anymore :(

**Expected behavior**

The link should point to [this new page](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/creating-and-using-encrypted-secrets).

**Comment by jeffpaul** [comment]
Welcome to our GitHub Actions and thanks for the report @felipeelia!  Mind making the same update to the https://github.com/10up/action-wordpress-plugin-asset-update repo as well?

**Comment by felipeelia** [comment]
Thank you @jeffpaul! I'm happy to (modestly) retribute the effort you folks put on it. I've opened a [PR](https://github.com/10up/action-wordpress-plugin-asset-update/pull/11) with the same fix there as well. Let me know if there is something else where I can help, ok?

**Comment by jeffpaul** [comment]
@felipeelia there's some ["help wanted"+"good first issues"](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aopen+is%3Aissue+org%3A10up+label%3A%22help+wanted%22+label%3A%22good+first+issue%22) scattered across 10up's repos, but if there's one of our projects or a type of work you're most comfortable with I'd be happy to dig some more specific items up... just let me know!

**Comment by felipeelia** [comment]
I'll give a look, for sure! Thanks once more @jeffpaul
