### ISSUE TITLE
Where do I add my SVN credentials?

### ISSUE THREAD

**Issue by wolffe** [10up/action-wordpress-plugin-deploy#2]
Where do I add my SVN credentials? Is there a physical secrets file anywhere in my repo?

**Comment by fabianmarz** [comment]
The secrets are defined in our Repo. See [this](https://help.github.com/en/articles/virtual-environments-for-github-actions#creating-and-using-secrets-encrypted-variables) man page for exact information.

**Comment by helen** [comment]
@wolffe Sorry I missed this! Yes, they go in your repo settings. Thanks for the link, @fabianmarz! Looks like we should update the link in this repo's README, if anybody is interested in a PR for that.

**Comment by helen** [comment]
I added the link to the readme, let me know if there are any other instructions I can clarify!
