### ISSUE TITLE
##[error]Docker run failed with exit code 1

### ISSUE THREAD

**Issue by mobeenabdullah** [10up/action-wordpress-plugin-deploy#21]
I'm trying to deploy my plugin on SVN but it is giving me this "##[error]Docker run failed with exit code 1" error. Below is the Repo  URL:
https://github.com/mobeenabdullah/WP-Select-Primary-Category/

Below is the error details in the screenshot URL:
https://ibb.co/JmxpzTv

Waiting for the kind help.

Best,
Mobeen A.

**Comment by mobeenabdullah** [comment]
Here's the link with "Runs" details:
https://github.com/mobeenabdullah/WP-Select-Primary-Category/runs/363296585

**Comment by mobeenabdullah** [comment]
Update:
I was missing out the "tag" as in version number with the push, that was causing the issue :)

**Comment by igorchernenko92** [comment]
I have the same problem. @mobeenabdullah Could you describe what you did more fully ?
