### ISSUE TITLE
shellcheck in CI

### ISSUE THREAD

**Issue by szepeviktor** [10up/action-wordpress-plugin-deploy#29]
Please consider introducing shellcheck in CI https://github.com/marketplace/actions/shellcheck

**Comment by szepeviktor** [comment]
There is no CI 😲

**Comment by helen** [comment]
Well, no, there wasn't, but only took a few minutes to add in #34.

Failure: https://github.com/10up/action-wordpress-plugin-deploy/pull/34/checks?check_run_id=558707518#step:4:4
Success: https://github.com/10up/action-wordpress-plugin-deploy/runs/558713421

**Comment by szepeviktor** [comment]
Urgy-mergy!
