### ISSUE TITLE
Add steps to example workflow around ZIP generation

### ISSUE THREAD

**Issue by helen** [10up/action-wordpress-plugin-deploy#4]
**Is your enhancement related to a problem? Please describe.**
With the new `.distignore` method of excluding files from deployment, the GitHub-generated ZIP file attached to releases no longer reflects what gets deployed to .org. Also, broadly that automatic naming is an issue, as you'll get `plugin-slug-X.Y.Z` as the folder name upon unzipping, which is not really what you or WordPress want.

**Describe the solution you'd like**
Test additional steps in a test repo workflow and then add them to `README.md`. My sense is that existing Actions can be leveraged to generate the ZIP and attach it to a release, but don't know yet. If not, we can write one, which will also be useful for plugins that don't release to .org at all and update directly from GH instead.

**Comment by shivapoudel** [comment]
Ref: https://github.com/10up/actions-wordpress/issues/8#issuecomment-624542152
