### ISSUE TITLE
Non-existent assets directory causes failure

### ISSUE THREAD

**Issue by helen** [10up/action-wordpress-plugin-deploy#7]
**Describe the bug**
Pretty much as described. While perhaps not a best practice, there are plugins out there without screenshots or branding imagery.

**Steps to Reproduce**
1. Tag a release on a repo without a `.wordpress-org` directory.
2. Check Action run.
3. See error

```
rsync: change_dir "/github/workspace/.wordpress-org" failed: No such file or directory (2)
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1207) [sender=3.1.3]
##[error]Docker run failed with exit code 23
```

**Expected behavior**
It should check for the directory and skip if doesn’t exist.

**Additional context**
This is a companion issue to describe the problem #6 is solving. A parallel one will need to be opened for the asset updater action.

**Comment by robogeek** [comment]
I have the same problem.  I see there's a pull request underway to fix the problem.  I'd like to know when this is finished.  Thank you very much.
